name: ibrnet
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2021.1.19=h06a4308_1
  - certifi=2020.12.5=py37h06a4308_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1k=h27cfd23_0
  - pip=21.0.1=py37h06a4308_0
  - python=3.7.10=hdb3f193_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py37h06a4308_0
  - sqlite=3.35.2=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.12.0
    - astor==0.8.1
    - cached-property==1.5.2
    - chardet==4.0.0
    - configargparse==1.4
    - cycler==0.10.0
    - decorator==4.4.2
    - ffmpeg==1.4
    - filelock==3.0.12
    - future==0.18.2
    - gast==0.2.2
    - gdown==3.12.2
    - google-pasta==0.2.0
    - grpcio==1.36.1
    - h5py==3.2.1
    - idna==2.10
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.3
    - importlib-metadata==3.7.3
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - matplotlib==3.3.4
    - networkx==2.5
    - numpy==1.20.1
    - opencv-python==4.5.1.48
    - opt-einsum==3.3.0
    - pillow==8.1.2
    - protobuf==3.15.6
    - pyparsing==2.4.7
    - pysocks==1.7.1
    - python-dateutil==2.8.1
    - pytube==10.6.0
    - pywavelets==1.1.1
    - requests==2.25.1
    - scikit-image==0.18.1
    - scipy==1.6.2
    - six==1.15.0
    - tensorboard==1.15.0
    - tensorboardx==2.1
    - tensorflow==1.15.0
    - tensorflow-estimator==1.15.1
    - tensorflow-gpu==1.15.0
    - termcolor==1.1.0
    - thop==0.0.31-2005241907
    - tifffile==2021.3.17
    - torch==1.5.1
    - torchvision==0.6.1
    - tqdm==4.59.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.4
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - zipp==3.4.1
prefix: /phoenix/S7/qw246/anaconda3/envs/ibrnet

